export const POSTS_GET_POSTS_SUCCESS = "POSTS_GET_POSTS_SUCCESS";
export const POST_GET_NEXT_PAGE = "POST_GET_NEXT_PAGE";
export const POST_GET_POST_BY_ID_SUCCESS = "POST_GET_POST_BY_ID_SUCCESS";
export const POST_FIND_POST_BY_ID = "POST_FIND_POST_BY_ID";
export const POST_RESET_POST = "POST_RESET_POST";
export const POSTS_LOADING_START = "POSTS_LOADING_START";
export const POSTS_LOADING_END = "POSTS_LOADING_END";

export const COMMENT_LOADING_START = "COMMENT_LOADING_START";
export const COMMENT_LOADING_END = "COMMENT_LOADING_START_END";
export const COMMENT_GET_POST_COMMENT_SUCCESS =
  "COMMENT_GET_POST_COMMENT_SUCCESS";

export const AUTH_SET_USER = "AUTH_SET_USER";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_SET_ERROR = "AUTH_SET_ERROR";

export const USER_GET_USER_SUCCESS = "USER_GET_USER_SUCCESS";
export const USER_GET_USER_BY_ID_SUCCESS = "USER_GET_USER_BY_ID_SUCCESS";
export const USER_LOADING_START = "USER_LOADING_START";
export const USER_LOADING_END = "USER_LOADING_END";

export const ANNO_GET_ANNO_SUCCESS = "ANNO_GET_ANNO_SUCCESS";
export const ANNO_GET_ANNO_BY_ID_SUCCESS = "ANNO_GET_ANNO_BY_ID_SUCCESS";
export const ANNO_GET_NEXT_PAGE = "ANNO_GET_NEXT_PAGE";
export const ANNO_RESET_ANNO = "ANNO_RESET_POST";
export const ANNO_LOADING_START = "ANNO_LOADING_START";
export const ANNO_LOADING_END = "ANNO_LOADING_END";
